name: deploy
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.15'
      - name: Install dependencies
        run: yarn install
      - name: Run build task
        run: yarn build
